# Generated by Django 2.2.4 on 2019-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=15, unique=True)),
                ('dept', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('B1', '大一'), ('B2', '大二'), ('B3', '大三'), ('B4', '大四'), ('M1', '碩一'), ('M2', '碩二')], max_length=2)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('UR', '審核中'), ('M', '已入社'), ('NP', '未付款')], default='UR', max_length=2)),
            ],
        ),
    ]
