# Generated by Django 2.2.5 on 2019-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('NO', '無法領獎'), ('YET', '尚未領獎'), ('TIX', '已使用票券領獎'), ('FORM', '已填表單領獎'), ('MIX', '已填表單加使用票券領獎')], default='NO', max_length=4)),
            ],
        ),
    ]
